name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # To run this worlfow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-tp-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF_ACCESS_TOKEN: ${{ secrets.HF_ACCESS_TOKEN }}
        run: git remote add space https://jcmeunier:$HF_ACCESS_TOKEN@huggingface.co/spaces/jcmeunier/01-demo-text-summarization
      - name: Push to hub
        env:
          HF_ACCESS_TOKEN: ${{ secrets.HF_ACCESS_TOKEN }}
        run: git push --force https://jcmeunier:$HF_ACCESS_TOKEN@huggingface.co/spaces/jcmeunier/01-demo-text-summarization main        




### Template version

# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request evnets but only for the main branch 
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentia&lly or in parallel

# jobs:
#   # This workflow contains a single job called 'build'
#   build:
#     # The type of runner that the job will run on 
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of command using the runners shell
#       - name: TRun a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
          
